spring:
  application:
    name: springboot-redisson
  redis:
    redisson:
      file: classpath:redisson.yml
  main:
    web-application-type: reactive

server:
  port: 9899 #9899

liteflow:
  rule-source: config/flow.el.xml



